# Generated by Django 5.0.2 on 2024-03-17 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('dataVencimento', models.DateField()),
                ('prioridade', models.IntegerField(choices=[(1, 'Baixa'), (2, 'Media'), (3, 'Alta')], default=2)),
                ('finalizada', models.BooleanField(default=False)),
            ],
        ),
    ]
